import {masterAnimations} from './MasterAnimationData';
import {conditionAnimations} from './ConditionAnimationData';
import {masterCharacterData} from './MasterSpriteData';
import {masterFrameUrl,masterFrameStyle,masterFrameBounds} from './MasterAnimations';
import {deathScene} from './DeathScene';
import '../death.css';
const root=document.querySelector<HTMLElement>('#condition-preview')!;
const params=new URLSearchParams(location.search);
const style=document.createElement('style');style.textContent=`@font-face{font-family:'Luckiest Guy';src:url('/assets/fonts/LuckiestGuy-Regular.ttf')}*{box-sizing:border-box}body{margin:0;background:#111927;color:#ffeed4;font-family:system-ui}main{max-width:1040px;margin:auto;padding:18px}h1{font-size:24px}label{display:inline-grid;gap:5px;margin:10px}select,button{font:inherit;background:#25334b;color:#fff;border:1px solid #9c8662;padding:10px;border-radius:8px}.stage{position:relative;width:min(70vh,100%);aspect-ratio:1;margin:auto;background:#182238;border-radius:18px}.stage img{position:absolute;object-fit:fill}.stage.closeup img{scale:3;transform-origin:50% 20%}.table{position:absolute;left:-10%;right:-10%;top:54%;height:39%;background:#1d2632;border:2px solid #ba9256;border-radius:50%;pointer-events:none;display:none}.table.show{display:block}p{line-height:1.5}.primary-button{background:#c1a46a;color:#201728;border-radius:8px}.eyebrow{letter-spacing:.18em;font-size:12px}`;document.head.append(style);
root.innerHTML=`<main><h1>100next · Condition animation review</h1><p>Complete character drawings, actual rounded card backs, fixed canvas. Preview does not change game statistics.</p><label>Character<select id="character">${masterCharacterData.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}</select></label><label>Condition<select id="condition"><option value="0">Healthy</option><option value="1">1 · Bruised</option><option value="2">2 · Torn clothing</option><option value="3">3 · Bandaged</option></select></label><label>Expression<select id="emotion">${['calm','focused','nervous','panicked','amused','confident','defeated'].map(c=>`<option>${c}</option>`).join('')}</select></label><label>Animation<select id="clip">${['throw','receive','blink','look-left','look-right','study','tumble','return','death'].map(c=>`<option>${c}</option>`).join('')}</select></label><button id="play">Replay</button><label><input type="checkbox" id="loop">Repeat</label><label><input type="checkbox" id="face">Face close-up</label><label><input type="checkbox" id="table">Table cover</label><div class="stage"><img alt="Character animation"><div class="table"></div></div><p id="details"></p><a href="/">Return to game</a></main>`;
const character=root.querySelector<HTMLSelectElement>('#character')!,condition=root.querySelector<HTMLSelectElement>('#condition')!,clip=root.querySelector<HTMLSelectElement>('#clip')!,img=root.querySelector<HTMLImageElement>('.stage img')!;
character.value=params.get('character')??'finn';condition.value=params.get('condition')??'1';clip.value=params.get('clip')??'throw';let epoch=0,timer=0,paused=false,seek:((delta:number)=>void)|undefined;
const controls=document.createElement('div');controls.innerHTML='<button id="previous-frame">← Previous frame</button> <button id="pause">Pause</button> <button id="next-frame">Next frame →</button> <output id="frame-position" aria-live="polite"></output>';root.querySelector('.stage')!.before(controls);
root.querySelector('#emotion')!.insertAdjacentHTML('beforeend','<option value="held">Holding one card</option>');
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
async function play(){clearTimeout(timer);const ticket=++epoch,id=character.value,stage=+condition.value,set=stage?conditionAnimations[id]?.[stage]:masterAnimations[id];root.querySelector('.death-scene')?.remove();if(!set)return;
 params.set('character',id);params.set('condition',String(stage));params.set('clip',clip.value);history.replaceState(null,'','?'+params);
 if(clip.value==='death'){const index=masterCharacterData.findIndex(c=>c.id===id);root.insertAdjacentHTML('beforeend',deathScene({name:masterCharacterData[index].name,avatar:index} as never,-16,20,escape));return;}
 const emotion=root.querySelector<HTMLSelectElement>('#emotion')!.value,pose=emotion==='held'?set.clips.throw.frames.at(-1)!:set.emotions[emotion]??'rest';
 const key=clip.value==='blink'?`blink-${pose}`:set.clips[`${clip.value}@${pose}`]?`${clip.value}@${pose}`:clip.value;
 const ready=set.clips['receive-ready'];
 const action=clip.value==='receive'?{frames:[...ready.frames,ready.frames.at(-1)!,...set.clips.pickup.frames],durations:[...ready.durations,450,...set.clips.pickup.durations]}:set.clips[key];if(!action)return;
 root.querySelector('#details')!.textContent=`${masterCharacterData.find(c=>c.id===id)?.name} · ${stage?`Condition ${stage}`:'Healthy'} · ${action.frames.length} frames · ${action.durations.reduce((a,b)=>a+b,0)} ms`;
 await Promise.all([...new Set(action.frames)].map(frame=>{const image=new Image();image.src=masterFrameUrl(id,frame,stage);return image.decode()}));if(ticket!==epoch)return;
 let frame=0;function paint(){if(ticket!==epoch)return;img.src=masterFrameUrl(id,action.frames[frame],stage);const [x,y,w,h]=masterFrameBounds(id,action.frames[frame],stage);img.style.cssText=masterFrameStyle(id,action.frames[frame],stage)+(root.querySelector<HTMLInputElement>('#face')!.checked?`;transform-origin:${(1024-x)/w*100}% ${(650-y)/h*100}%;transform:scale(3)`:'');root.querySelector('#frame-position')!.textContent=`Frame ${frame+1}/${action.frames.length} · ${action.frames[frame]}`;}
 function step(){paint();if(paused)return;if(frame<action.frames.length-1)timer=window.setTimeout(()=>{frame++;step()},action.durations[frame]);else if(root.querySelector<HTMLInputElement>('#loop')!.checked)timer=window.setTimeout(()=>void play(),1000);}
 seek=delta=>{clearTimeout(timer);frame=Math.max(0,Math.min(action.frames.length-1,frame+delta));step()};step();
}
root.querySelector('#pause')!.addEventListener('click',e=>{paused=!paused;(e.target as HTMLElement).textContent=paused?'Resume':'Pause';clearTimeout(timer);seek?.(0)});
for(const [selector,delta] of [['#previous-frame',-1],['#next-frame',1]] as const)root.querySelector(selector)!.addEventListener('click',()=>{paused=true;root.querySelector('#pause')!.textContent='Resume';seek?.(delta)});
root.querySelector('#loop')!.addEventListener('change',()=>void play());
for(const select of [character,condition,clip,root.querySelector<HTMLSelectElement>('#emotion')!])select.addEventListener('change',()=>void play());root.querySelector('#play')!.addEventListener('click',()=>void play());root.addEventListener('click',e=>{if((e.target as HTMLElement).closest('[data-action="dismiss-death"]'))root.querySelector('.death-scene')?.remove()});root.querySelector('#table')!.addEventListener('change',e=>root.querySelector('.table')!.classList.toggle('show',(e.target as HTMLInputElement).checked));void play();
root.querySelector('#face')!.addEventListener('change',e=>{root.querySelector<HTMLElement>('.stage')!.style.overflow=(e.target as HTMLInputElement).checked?'hidden':'';void play()});
