import {conditionAnimations} from './ConditionAnimationData';
import {masterCharacterData} from './MasterSpriteData';
import {masterFrameUrl,masterFrameStyle} from './MasterAnimations';
import {deathScene} from './DeathScene';
import '../death.css';
const root=document.querySelector<HTMLElement>('#condition-preview')!;
const params=new URLSearchParams(location.search);
const style=document.createElement('style');style.textContent=`@font-face{font-family:'Luckiest Guy';src:url('/assets/fonts/LuckiestGuy-Regular.ttf')}*{box-sizing:border-box}body{margin:0;background:#111927;color:#ffeed4;font-family:system-ui}main{max-width:1040px;margin:auto;padding:18px}h1{font-size:24px}label{display:inline-grid;gap:5px;margin:10px}select,button{font:inherit;background:#25334b;color:#fff;border:1px solid #9c8662;padding:10px;border-radius:8px}.stage{position:relative;width:min(70vh,100%);aspect-ratio:1;margin:auto;background:#182238;border-radius:18px}.stage img{position:absolute;object-fit:fill}.table{position:absolute;left:-10%;right:-10%;top:54%;height:39%;background:#1d2632;border:2px solid #ba9256;border-radius:50%;pointer-events:none;display:none}.table.show{display:block}p{line-height:1.5}.primary-button{background:#c1a46a;color:#201728;border-radius:8px}.eyebrow{letter-spacing:.18em;font-size:12px}`;document.head.append(style);
root.innerHTML=`<main><h1>100next · Condition animation review</h1><p>Complete character drawings, actual rounded card backs, fixed canvas. Preview does not change game statistics.</p><label>Character<select id="character">${masterCharacterData.map(c=>`<option value="${c.id}">${c.name}</option>`).join('')}</select></label><label>Condition<select id="condition"><option value="1">1 · Bruised</option><option value="2">2 · Torn clothing</option><option value="3">3 · Bandaged</option></select></label><label>Animation<select id="clip">${['throw','receive','blink','look-left','look-right','study','tumble','return','death'].map(c=>`<option>${c}</option>`).join('')}</select></label><button id="play">Replay</button><label><input type="checkbox" id="table">Table cover</label><div class="stage"><img alt="Character animation"><div class="table"></div></div><p id="details"></p><a href="/">Return to game</a></main>`;
const character=root.querySelector<HTMLSelectElement>('#character')!,condition=root.querySelector<HTMLSelectElement>('#condition')!,clip=root.querySelector<HTMLSelectElement>('#clip')!,img=root.querySelector<HTMLImageElement>('.stage img')!;
character.value=params.get('character')??'finn';condition.value=params.get('condition')??'1';clip.value=params.get('clip')??'throw';let epoch=0,timer=0;
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
async function play(){clearTimeout(timer);const ticket=++epoch,id=character.value,stage=+condition.value,set=conditionAnimations[id]?.[stage];root.querySelector('.death-scene')?.remove();if(!set)return;
 params.set('character',id);params.set('condition',String(stage));params.set('clip',clip.value);history.replaceState(null,'','?'+params);
 if(clip.value==='death'){const index=masterCharacterData.findIndex(c=>c.id===id);root.insertAdjacentHTML('beforeend',deathScene({name:masterCharacterData[index].name,avatar:index} as never,-16,20,escape));return;}
 const action=clip.value==='receive'?{frames:[...set.clips['receive-ready'].frames,...set.clips.pickup.frames],durations:[80,70,490,...set.clips.pickup.durations]}:set.clips[clip.value==='blink'?'blink-rest':clip.value];if(!action)return;
 root.querySelector('#details')!.textContent=`${masterCharacterData.find(c=>c.id===id)?.name} · Condition ${stage} · ${action.frames.length} frames · ${action.durations.reduce((a,b)=>a+b,0)} ms`;
 await Promise.all([...new Set(action.frames)].map(frame=>{const image=new Image();image.src=masterFrameUrl(id,frame,stage);return image.decode()}));if(ticket!==epoch)return;
 let frame=0;function step(){if(ticket!==epoch)return;img.src=masterFrameUrl(id,action.frames[frame],stage);img.style.cssText=masterFrameStyle(id,action.frames[frame],stage);if(frame<action.frames.length-1)timer=window.setTimeout(step,action.durations[frame++]);}step();
}
for(const select of [character,condition,clip])select.addEventListener('change',()=>void play());root.querySelector('#play')!.addEventListener('click',()=>void play());root.addEventListener('click',e=>{if((e.target as HTMLElement).closest('[data-action="dismiss-death"]'))root.querySelector('.death-scene')?.remove()});root.querySelector('#table')!.addEventListener('change',e=>root.querySelector('.table')!.classList.toggle('show',(e.target as HTMLInputElement).checked));void play();
