import assert from 'node:assert/strict';
import { build } from 'esbuild';
const bundle=await build({entryPoints:['src/game/points.ts'],bundle:true,platform:'node',format:'esm',write:false});
const {accountPoints,gamePoints,localPointsKey,LocalPoints}=await import(`data:text/javascript;base64,${Buffer.from(bundle.outputFiles[0].text).toString('base64')}`);
assert.equal(accountPoints({survives:20,exacts:3,setups:4,busts:2}),17);
assert.equal(accountPoints({}),0);
const players=[{id:0,name:' Guest ',avatar:0,kind:'human',ratingDelta:1,lifetimePoints:10},{id:1,name:'Finn',avatar:1,kind:'cpu',ratingDelta:-5}];
const state={players,phase:'playing',match:{scores:[3,0]}};
assert.equal(gamePoints(state,0),4,'Show an exact-100 award before the round settles');
state.phase='ended';state.match.scores=[4,-5];
assert.equal(gamePoints(state,0),4,'Settled points must not be counted twice');
assert.equal(gamePoints({...state,phase:'playing',match:{scores:[0,0]},players:players.map(player=>({...player,ratingDelta:0}))},0),0,'A new game starts at zero');
const values=new Map();const storage={getItem:key=>values.get(key)??null,setItem:(key,value)=>values.set(key,value)};
const history=new LocalPoints(storage),humanKey=localPointsKey(players[0],'midnight'),cpuKey=localPointsKey(players[1],'midnight');
assert.equal(humanKey,localPointsKey({...players[0],name:'guest',avatar:15},'observatory'),'Guest history follows the name, not the artwork');
assert.notEqual(cpuKey,localPointsKey(players[1],'observatory'),'Different casts keep separate CPU histories');
history.set(humanKey,10);history.set(cpuKey,7);history.settle(state,'midnight');history.settle(state,'midnight');
assert.deepEqual(players.map(player=>player.lifetimePoints),[11,2]);
assert.equal(new LocalPoints(storage).get(humanKey),11,'Guest history survives reopening');
const signedState={...state,players:players.map(player=>({...player})),phase:'ended'};
history.settle(signedState,'midnight',0);
assert.equal(history.get(humanKey),11,'Signed-in points must not be added to a guest history');
assert.equal(signedState.players[0].lifetimePoints,12);
const blocked=new LocalPoints({getItem(){throw Error('Unavailable');},setItem(){throw Error('Unavailable');}});
blocked.set(humanKey,9);assert.equal(blocked.get(humanKey),9);
console.log('Points checks passed: lifetime awards, current-game reset, settled-score display, persistent guest/CPU histories, duplicate protection and account isolation.');
