import type { AccountClient } from './AccountClient';
import { accountPoints } from '../game/points';
import type { AccountStats } from './model';
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function statsGrid(stats:AccountStats):string {
  return `<div class="stats-grid">${Object.entries({'All-time net points':accountPoints(stats),Freedom:stats.freedoms,Death:stats.deaths,Rounds:stats.rounds,'Exact 100s':stats.exacts,Survivals:stats.survives,Overflows:stats.busts,'Cards played':stats.cards,'Setups':stats.setups,'Choose Player':stats.sevens,Reverse:stats.eights,Zero:stats.nines,'Minus Ten':stats.tens}).map(([label,value])=>`<div><span>${label}</span><strong>${value}</strong></div>`).join('')}</div>`;
}
export function accountStatistics(account:AccountClient):string {
  return `<h2>${escape(account.snapshot.user!.username)} · Statistics</h2><p>Overall points: <strong>${account.overallPoints}</strong></p><h3>Online · Server verified</h3>${statsGrid(account.snapshot.online)}<h3>Local practice · Player reported</h3>${statsGrid(account.snapshot.practice)}<p>These statistics follow your account across devices. Guest history stays on its original device. Death is recorded once when a settled match score reaches −16 or below. Online results are server verified; local practice remains player reported. Freedom at +30 overall points or +30 game points after a settled round. Freedom and Death reset overall points to 0; these all-time statistics are retained.</p>`;
}
export function accountView(account:AccountClient):string {
  const {user}=account.snapshot;
  const error=account.error?`<p class="account-error" role="alert">${escape(account.error)}</p>`:'';
  const disabled=account.busy?'disabled':'';
  if(user)return `<h2>Your account</h2><p class="account-name">${escape(user.username)}</p>${account.recoveryCode?`<section class="recovery-note"><h3>Save your recovery code</h3><p>There is no email recovery. Keep this code somewhere private. You’ll need it if you forget your password.</p><code>${escape(account.recoveryCode)}</code><button class="secondary-button" data-action="copy-recovery">Copy code</button><button class="text-button" data-action="saved-recovery">I saved it</button></section>`:''}<p>Signed in on this device. Your online and practice statistics are saved to your account.</p>${error}<div class="menu-actions"><button class="primary-button" data-action="stats">View my statistics</button><button class="secondary-button" data-action="account-logout" ${disabled}>${account.busy?'Please wait…':'Sign out'}</button></div>`;
  const mode=account.mode,title=mode==='register'?'Create account':mode==='recover'?'Recover account':'Sign in';
  return `<h2>${title}</h2><p>Keep your statistics wherever you play. Or close this and keep playing as a guest.</p><div class="account-tabs"><button data-account-mode="login" aria-pressed="${mode==='login'}">Sign in</button><button data-account-mode="register" aria-pressed="${mode==='register'}">Create account</button></div><form id="account-form"><label>NAME<input name="username" aria-label="Account name" autocomplete="username" pattern="[A-Za-z0-9_]{3,15}" minlength="3" maxlength="15" required ${disabled}></label><small>3–15 letters, numbers or underscores. Names are unique.</small>${mode==='recover'?`<label>RECOVERY CODE<input name="recoveryCode" aria-label="Recovery code" autocomplete="off" required ${disabled}></label>`:''}<label>${mode==='recover'?'NEW PASSWORD':'PASSWORD'}<input name="password" aria-label="${mode==='recover'?'New password':'Password'}" type="password" autocomplete="${mode==='login'?'current-password':'new-password'}" minlength="${mode==='login'?1:12}" maxlength="128" required ${disabled}></label>${mode==='login'?'':'<small>At least 12 characters. A few words work well.</small>'}${error}<button type="submit" class="primary-button" ${disabled}>${account.busy?'Please wait…':title}</button></form><button class="text-button" data-account-mode="recover">Forgot your password?</button>${mode==='register'?'<p>No email needed. We’ll give you a recovery code after signup.</p>':''}`;
}
